// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udjdyjeyydudniiqoips.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkamR5amV5eWR1ZG5paXFvaXBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMjc3NjgsImV4cCI6MjA2MTcwMzc2OH0.gE8XbH3olqtdGE-IKhnFlsQK82lb8FQiAbExdZcMd-U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);